{% set name = "dagster-cloud-cli" %}
{% set version = "1.8.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dagster-cloud-cli-{{ version }}.tar.gz
  sha256: 1f5798c943eb190856e87b298a655460f9df00f5de56e57ddaee8b5973a384e9

build:
  entry_points:
    - dagster-cloud = dagster_cloud_cli.entrypoint:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - click
    - freezegun
    - pydantic
    - pytest
    - typing_extensions
    - python >=3.8
    - dagster ==1.8.5
    - packaging >=20.9
    - questionary
    - requests
    - typer >=0.4.1
    - pyyaml >=5.1
    - github3.py

test:
  imports:
    - dagster_cloud_cli
    - dagster_cloud_cli_tests
  commands:
    - pip check
    - dagster-cloud --help
  requires:
    - pip

about:
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/dagster-io/dagster-cloud
  summary: CLI for Dagster Cloud

extra:
  recipe-maintainers:
    - geoHeil
    - tmirko
    - milicevica23
