{% set min_python = "python >=3.8,<3.13" %}
{% set min_python = "python >=3.8,<3.13" %}
{% set min_python = "python >=3.8,<3.13" %}
{% set min_python = "python >=3.8,<3.13" %}
{% set min_python = "python >=3.8,<3.13" %}
{% set min_python = "python >=3.8,<3.13" %}
{% set min_python = "python >=3.8,<3.13" %}
{% set min_python = "python >=3.8,<3.13" %}
{% set min_python = "python >=3.8,<3.13" %}
{% set min_python = "python >=3.8,<3.13" %}
{% set min_python = "python >=3.8,<3.13" %}
{% set min_python = "python >=3.8,<3.13" %}
{% set min_python = "python >=3.8,<3.13" %}
{% set min_python = "python >=3.8,<3.13" %}
{% set min_python = "python >=3.8,<3.13" %}
{% set min_python = "python >=3.8,<3.13" %}
{% set min_python = "python >=3.8,<3.13" %}
{% set min_python = "python >=3.8,<3.13" %}
{% set min_python = "python >=3.8,<3.13" %}
{% set min_python = "python >=3.8,<3.13" %}
{% set min_python = "python >=3.8,<3.13" %}
{% set min_python = "python >=3.8,<3.13" %}
{% set min_python = "python >=3.8,<3.13" %}
{% set min_python = "python >=3.8,<3.13" %}
{% set min_python = "python >=3.8,<3.13" %}
{% set min_python = "python >=3.8,<3.13" %}
{% set min_python = "python >=3.8,<3.13" %}
{% set min_python = "python >=3.8,<3.13" %}
{% set min_python = "python >=3.8,<3.13" %}
{% set min_python = "python >=3.8,<3.13" %}
{% set name = "dagster-cloud-cli" %}
{% set version = "1.10.5" %}
{% set min_python = "python >=3.8,<3.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 14c73de396e78ed6407294ac1d04832c49835b31ac4a24a513f620425ae78e70

build:
  entry_points:
    - dagster-cloud = dagster_cloud_cli.entrypoint:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - {{ min_python }}
    - pip
    - setuptools
  run:
    - jinja2
    - click
    - freezegun
    - pydantic
    - pytest
    - typing_extensions
    - {{ min_python }}
    - dagster ==1.10.5
    - packaging >=20.9
    - questionary
    - requests
    - typer >=0.4.1
    - pyyaml >=5.1
    - github3.py

test:
  imports:
    - dagster_cloud_cli
    - dagster_cloud_cli_tests
  commands:
    - pip check
    - dagster-cloud --help
  requires:
    - pip
    - python {{ python_min }}

about:
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/dagster-io/dagster-cloud
  summary: CLI for Dagster Cloud

extra:
  recipe-maintainers:
    - geoHeil
    - tmirko
    - milicevica23
