{% set min_python = "python >=3.8,<3.13" %}
{% set min_python = "python >=3.8,<3.13" %}
{% set name = "dagster-cloud-cli" %}
{% set version = "1.9.5" %}
{% set min_python = "python >=3.8,<3.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8893ec41cd8dc64f26fde0a1a36a40102fd4186d801314a42ca03e6b7f60b9b7

build:
  entry_points:
    - dagster-cloud = dagster_cloud_cli.entrypoint:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - {{ min_python }}
    - pip
    - setuptools
  run:
    - click
    - freezegun
    - pydantic
    - pytest
    - typing_extensions
    - {{ min_python }}
    - dagster ==1.9.5
    - packaging >=20.9
    - questionary
    - requests
    - typer >=0.4.1
    - pyyaml >=5.1
    - github3.py

test:
  imports:
    - dagster_cloud_cli
    - dagster_cloud_cli_tests
  commands:
    - pip check
    - dagster-cloud --help
  requires:
    - pip

about:
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/dagster-io/dagster-cloud
  summary: CLI for Dagster Cloud

extra:
  recipe-maintainers:
    - geoHeil
    - tmirko
    - milicevica23
