schema_version: 1

context:
  python_min: '3.9'
  name: dagster-cloud-cli
  version: "1.10.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 07f3778b39942877ada4a240366989d7d92c763af644aaf7b2c6e5123f6f8fec

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - dagster-cloud = dagster_cloud_cli.entrypoint:app

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - jinja2
    - click
    - freezegun
    - pydantic
    - pytest
    - typing_extensions
    - python ${{ python_min }}.*
    - dagster == ${{ version }}
    - dagster-shared
    - packaging >=20.9
    - questionary
    - requests
    - typer >=0.4.1
    - pyyaml >=5.1
    - github3.py

tests:
  - python:
      imports:
        - dagster_cloud_cli
        - dagster_cloud_cli_tests
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
      - dagster-cloud --help

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: CLI for Dagster Cloud
  homepage: https://github.com/dagster-io/dagster-cloud

extra:
  recipe-maintainers:
    - geoHeil
    - tmirko
    - milicevica23
